name: Build from Containerfile
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      REGISTRY: platformghruntest.azurecr.io
      CR_USERNAME: ${{ secrets.CR_USERNAME }}
      CR_PASSWORD: ${{ secrets.CR_PASSWORD }}
    steps:
    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Buildah Action
      id: build
      uses: redhat-actions/buildah-build@v2
      with:
        image: github-actions-runner
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./Dockerfile

    - name: Log in to Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.CR_USERNAME }}
        password: ${{ env.CR_PASSWORD }}
        
    - name: Push to Container Repository
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        registry: ${{ env.REGISTRY }}
