name: build-freecredit
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: freecreditghrunner.azurecr.io
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_FC }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_FC }}
    steps:
    - uses: actions/checkout@v4
    - name: 'Azure login'
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        repository: bengtfredh/container-apps-ci-cd-runner
    - name: Buildah Action
      id: build
      uses: redhat-actions/buildah-build@v2
      with:
        image: github-actions-runner
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./Dockerfile
    - name: Push to Container Repository
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        registry: ${{ env.REGISTRY }}
