name: build-freecredit
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "22 2 * * *"

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: freecreditghrunner.azurecr.io
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_FC }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_FC }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_FC }}
    steps:
    - uses: actions/checkout@v4
    - name: 'Azure login'
      uses: azure/login@v2
      with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        repository: bengtfredh/container-apps-ci-cd-runner
    - name: Buildah Action
      id: build
      uses: redhat-actions/buildah-build@v2
      with:
        image: github-actions-runner
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./Dockerfile
    - name: Log in to Container registry
      run: podman login ${{ env.REGISTRY }} -u 00000000-0000-0000-0000-000000000000 -p $(az acr login --name ${{ env.REGISTRY }} --expose-token --output tsv --query accessToken --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID_FC }} --only-show-errors)
    - name: Push to Container Repository
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        registry: ${{ env.REGISTRY }}
